version: '3.8'
services:
  mongodb_test:
    image: mongo:latest
    container_name: persistence_mongo_test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 2s
      retries: 10

  neo4j_test:
    image: neo4j:latest
    container_name: persistence_neo4j_test
    ports:
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testpassword
    volumes:
      - neo4j_test_data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p testpassword 'RETURN 1;'"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  mongodb_test_data:
  neo4j_test_data:
